version: '3'

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5433:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db-data:
