version: '3'

services:

  telegram_bot:
    env_file: .env
    build:
      context: src/telegram_bot
      dockerfile: Dockerfile
    depends_on:
      - db

  vk_bot:
    env_file: .env
    build:
      context: src/vk_bot
      dockerfile: Dockerfile
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5433:5432"

volumes:
  db-data:
