version: '3'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: hello_speech_therapist
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  fastapi:
    env_file: .env
    build:
      context: ./src/db/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:root@db:5432/hello_speech_therapist
      PYTHONUNBUFFERED: 1

  telegram_bot:
    env_file: .env
    build:
      context: ./src/telegram_bot/
      dockerfile: Dockerfile
    depends_on:
      - fastapi
    environment:
      PYTHONUNBUFFERED: 1

  vk_bot:
    env_file: .env
    build:
      context: ./src/vk_bot/
      dockerfile: Dockerfile
    depends_on:
      - fastapi

volumes:
  db_data:
