"""Init migration with adding to_role_id in Link model

Revision ID: 0dd3f87c3be0
Revises: 
Create Date: 2024-07-27 17:49:10.481177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dd3f87c3be0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promocodes',
    sa.Column('promocode_id', sa.Integer(), nullable=False),
    sa.Column('promocode', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('promocode_id'),
    sa.UniqueConstraint('promocode')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('links',
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=250), nullable=False),
    sa.Column('link_name', sa.String(length=100), nullable=False),
    sa.Column('to_role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['to_role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('link_id'),
    sa.UniqueConstraint('link')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('fullname', sa.String(length=200), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('social_network', sa.Enum('TG', 'VK', name='socialnetworktype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('links')
    op.drop_table('roles')
    op.drop_table('promocodes')
    # ### end Alembic commands ###
