"""Initial migration

Revision ID: 16b8839c9b7d
Revises: 
Create Date: 2024-07-25 23:58:22.241432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16b8839c9b7d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=250), nullable=False),
    sa.Column('link_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('link_id'),
    sa.UniqueConstraint('link')
    )
    op.create_table('promocodes',
    sa.Column('promocode_id', sa.Integer(), nullable=False),
    sa.Column('promocode', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('promocode_id'),
    sa.UniqueConstraint('promocode')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('social_networks',
    sa.Column('social_network_id', sa.Integer(), nullable=False),
    sa.Column('social_network_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('social_network_id'),
    sa.UniqueConstraint('social_network_name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('fullname', sa.String(length=200), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('social_network_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.ForeignKeyConstraint(['social_network_id'], ['social_networks.social_network_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('social_networks')
    op.drop_table('roles')
    op.drop_table('promocodes')
    op.drop_table('links')
    # ### end Alembic commands ###
