"""Add notifications

Revision ID: 2fa551197c57
Revises: 387ad491f680
Create Date: 2024-08-16 20:35:22.382879

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2fa551197c57"
down_revision: Union[str, None] = "387ad491f680"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    notificationintervaltype = sa.Enum(
        "EVERY_DAY",
        "OTHER_DAY",
        "USER_CHOICE",
        name="notificationintervaltype",
    )
    notificationintervaltype.create(op.get_bind(), checkfirst=True)
    notificationweekdaytype = sa.Enum(
        "MONDAY",
        "TUESDAY",
        "WEDNESDAY",
        "THURSDAY",
        "FRIDAY",
        "SATURDAY",
        "SUNDAY",
        name="notificationweekdaytype",
    )
    notificationweekdaytype.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "tg_users", sa.Column("notificate_at", sa.Integer(), nullable=True)
    )
    op.add_column(
        "tg_users",
        sa.Column(
            "notification_interval", notificationintervaltype, nullable=True
        ),
    )
    op.add_column(
        "tg_users",
        sa.Column("notification_day", notificationweekdaytype, nullable=True),
    )
    op.add_column(
        "tg_users",
        sa.Column("notifications_enabled", sa.Boolean(), default=False),
    )
    op.execute(
        'UPDATE tg_users SET notifications_enabled = False WHERE notifications_enabled IS NULL'
    )
    op.alter_column('tg_users', 'notifications_enabled', nullable=False)
    op.add_column(
        "vk_users", sa.Column("notificate_at", sa.Integer(), nullable=True)
    )
    op.add_column(
        "vk_users",
        sa.Column(
            "notification_interval", notificationintervaltype, nullable=True
        ),
    )
    op.add_column(
        "vk_users",
        sa.Column("notification_day", notificationweekdaytype, nullable=True),
    )
    op.add_column(
        "vk_users",
        sa.Column("notifications_enabled", sa.Boolean(), default=False),
    )
    op.execute(
        'UPDATE vk_users SET notifications_enabled = False WHERE notifications_enabled IS NULL'
    )
    op.alter_column('vk_users', 'notifications_enabled', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vk_users", "notification_day")
    op.drop_column("vk_users", "notification_interval")
    op.drop_column("vk_users", "notificate_at")
    op.drop_column("vk_users", "notifications_enabled")
    op.drop_column("tg_users", "notification_day")
    op.drop_column("tg_users", "notification_interval")
    op.drop_column("tg_users", "notificate_at")
    op.drop_column("tg_users", "notifications_enabled")
    # ### end Alembic commands ###
