"""Add is_subscribed to users

Revision ID: 387ad491f680
Revises: f8c58df761ee
Create Date: 2024-08-16 16:21:29.140539

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '387ad491f680'
down_revision: Union[str, None] = 'f8c58df761ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_users', sa.Column('is_subscribed', sa.Boolean(), nullable=True))
    op.add_column('vk_users', sa.Column('is_subscribed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vk_users', 'is_subscribed')
    op.drop_column('tg_users', 'is_subscribed')
    # ### end Alembic commands ###
