"""notification

Revision ID: 5dee526fb34b
Revises: c4d3c2f48648
Create Date: 2024-08-10 14:53:50.531060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dee526fb34b'
down_revision: Union[str, None] = 'c4d3c2f48648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_users', sa.Column('notification_interval', sa.String(length=100), nullable=True))
    op.drop_column('tg_users', 'interval')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_users', sa.Column('interval', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('tg_users', 'notification_interval')
    # ### end Alembic commands ###
