"""Change link_type

Revision ID: 6408cdc9e9d1
Revises: 574c88214e01
Create Date: 2024-07-29 22:34:11.037528

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6408cdc9e9d1'
down_revision: Union[str, None] = '574c88214e01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('links', 'link_type',
               existing_type=postgresql.ENUM('URL', 'FILEPATH', name='linktype'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('links', 'link_type',
               existing_type=postgresql.ENUM('URL', 'FILEPATH', name='linktype'),
               nullable=True)
    # ### end Alembic commands ###
