"""Initial migration

Revision ID: 70546f04c6d1
Revises: 
Create Date: 2024-07-29 21:15:35.471624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70546f04c6d1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=250), nullable=False),
    sa.Column('link_name', sa.String(length=100), nullable=False),
    sa.Column('to_role', sa.Enum('PARENT', 'SPEECH_THERAPIST', name='roletype'), nullable=False),
    sa.PrimaryKeyConstraint('link_id'),
    sa.UniqueConstraint('link')
    )
    op.create_table('promocodes',
    sa.Column('promocode_id', sa.Integer(), nullable=False),
    sa.Column('promocode', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('promocode_id'),
    sa.UniqueConstraint('promocode')
    )
    op.create_table('tg_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('PARENT', 'SPEECH_THERAPIST', name='roletype'), nullable=False),
    sa.Column('is_admin', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('vk_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('PARENT', 'SPEECH_THERAPIST', name='roletype'), nullable=False),
    sa.Column('is_admin', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vk_users')
    op.drop_table('tg_users')
    op.drop_table('promocodes')
    op.drop_table('links')
    # ### end Alembic commands ###
