"""Fix Button foreign

Revision ID: 7c805d8a5bd8
Revises: bbd522d1ceff
Create Date: 2024-08-07 18:06:35.201429

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7c805d8a5bd8'
down_revision: Union[str, None] = 'bbd522d1ceff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buttons', sa.Column('parent_button_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'buttons', 'buttons', ['parent_button_id'], ['button_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'buttons', type_='foreignkey')
    op.drop_column('buttons', 'parent_button_id')
    # ### end Alembic commands ###
