"""notification

Revision ID: 91d4dbc8e2a9
Revises: 4d8ce9c52faf
Create Date: 2024-08-09 17:35:10.164146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91d4dbc8e2a9'
down_revision: Union[str, None] = '4d8ce9c52faf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
