"""notification

Revision ID: 92a96ece1da3
Revises: dfd9f544a4f4
Create Date: 2024-08-10 12:05:27.514111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92a96ece1da3'
down_revision: Union[str, None] = 'dfd9f544a4f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_users', sa.Column('interval', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_users', 'interval')
    # ### end Alembic commands ###
