"""Update enum

Revision ID: b23097430942
Revises: 2fa551197c57
Create Date: 2024-08-17 13:34:58.347647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b23097430942'
down_revision: Union[str, None] = '2fa551197c57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tg_users', 'notifications_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('vk_users', 'notifications_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vk_users', 'notifications_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tg_users', 'notifications_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
