"""notification

Revision ID: b90dc00c7872
Revises: f537c14aed79
Create Date: 2024-08-13 13:07:59.801084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b90dc00c7872'
down_revision: Union[str, None] = 'f537c14aed79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_users', sa.Column('notification_access', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_users', 'notification_access')
    # ### end Alembic commands ###
