"""Add Button model

Revision ID: bbd522d1ceff
Revises: b96824fc6b36
Create Date: 2024-08-07 17:54:06.998056

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bbd522d1ceff'
down_revision: Union[str, None] = 'b96824fc6b36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buttons',
    sa.Column('button_id', sa.Integer(), nullable=False),
    sa.Column('button_name', sa.String(length=100), nullable=False),
    sa.Column('button_type', sa.Enum('TEXT', 'GROUP', 'FILE', 'MAILING', 'ADMIN_MESSAGE', 'NOTIFICATION', name='buttontype'), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('to_role', ENUM(create_type=False, name='roletype'), nullable=True),
    sa.PrimaryKeyConstraint('button_id', name='pk_buttons'),
    sa.UniqueConstraint('button_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buttons')
    # ### end Alembic commands ###
