"""notification

Revision ID: bbdeee8d4e2f
Revises: 258e63db20e7
Create Date: 2024-08-09 14:18:06.179297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbdeee8d4e2f'
down_revision: Union[str, None] = '258e63db20e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_users', sa.Column('notificate_at', sa.Integer(), nullable=True))
    op.drop_column('tg_users', 'time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_users', sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.drop_column('tg_users', 'notificate_at')
    # ### end Alembic commands ###
