"""notification

Revision ID: c4d3c2f48648
Revises: 7c56c1ec76b7
Create Date: 2024-08-10 14:50:52.639025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4d3c2f48648'
down_revision: Union[str, None] = '7c56c1ec76b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tg_users', 'interval',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tg_users', 'interval',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
