"""Add Button is_in_main_menu

Revision ID: c556d3180c82
Revises: e97f2959560a
Create Date: 2024-08-13 09:15:27.758002

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c556d3180c82'
down_revision: Union[str, None] = 'e97f2959560a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buttons', sa.Column('is_in_main_menu', sa.Boolean(), nullable=True))
    op.alter_column('buttons', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('buttons', 'file_path',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('buttons', 'file_path',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('buttons', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('buttons', 'is_in_main_menu')
    # ### end Alembic commands ###
