name: Main Workflow

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd /home/yc-user/Privet_Logoped_team_4/
          git pull origin dev
          source /home/yc-user/Privet_Logoped_team_4/src/telegram_bot/venv/bin/activate
          pip install -r src/telegram_bot/requirements.txt
          alembic upgrade head
          deactivate
          source /home/yc-user/Privet_Logoped_team_4/src/vk_bot/venv/bin/activate
          pip install -r src/vk_bot/requirements.txt
          deactivate
          sudo systemctl restart docker-compose-db.service
          sudo systemctl restart telegram-bot.service
          sudo systemctl restart vk-bot.service
