name: Main Workflow

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
#   test:
#     runs-on: ubuntu-24.04

#     services:
#       postgres:
#         image: postgres:16
#         env:
#           POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
#           POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
#           POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
#         ports:
#           - 5432:5432
#         options: >-
#           --health-cmd "pg_isready -U ${{ secrets.POSTGRES_USER }}" 
#           --health-interval 10s 
#           --health-timeout 5s 
#           --health-retries 5

#       adminer:
#         image: adminer:4.8.1
#         ports:
#           - 8080:8080

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.12'

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt

#     - name: Run tests
#       env:
#         DATABASE_URL: postgres://postgres:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/${{ secrets.POSTGRES_DB }}
#       run: |
#         pytest

  deploy:
    runs-on: ubuntu-24.04
    # needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          cd /Privet_Logoped_team_4/
          git pull origin dev
          source /Privet_Logoped_team_4/src/telegram_bot/venv/bin/activate
          pip install -r src/telegram_bot/requirements.txt
          alembic upgrade head
          deactivate
          source /Privet_Logoped_team_4/src/vk_bot/venv/bin/activate
          pip install -r src/vk_bot/requirements.txt
          deactivate
          sudo systemctl restart docker-compose-db.service
          sudo systemctl restart telegram-bot.service
          sudo systemctl restart vk-bot.service
